### ISSUE TITLE
[UIX 2.1.1.1] Widgets server error log in Xenforo 2.1.1

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#1069]
````
ErrorException: Template error: Template public:_widget_thuix_aboutUsWidget is unknown src/XF/Template/Templater.php:618 

Generated by: boil26 Mar 23, 2019 at 3:37 PM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nadda/pub...', 618, Array)
#1 src/XF/Template/Templater.php(618): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(566): XF\Template\Templater->getTemplateData('public', '_widget_thuix_a...')
#3 src/XF/Template/Templater.php(1300): XF\Template\Templater->getTemplateCode('public', '_widget_thuix_a...')
#4 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('_widget_thuix_a...', Array, true)
#5 src/XF/Widget/Html.php(16): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:_widget_...', Array)
#6 internal_data/code_cache/widgets/_41_thuix_footer_aboutUsWidget.php(5): XF\Widget\Html->render()
#7 src/XF/Template/Templater.php(6649): XF\SubContainer\Widget->{closure}(Object(AddonFlare\PaidRegistrations\XF\Template\Templater), Array, Array)
#8 src/XF/SubContainer/Widget.php(168): XF\Template\Templater->renderWidgetClosure(Object(Closure), Array)
#9 src/XF/Template/Templater.php(1620): XF\SubContainer\Widget->getCompiledWidget(Array, Array)
#10 src/addons/ThemeHouse/UIX/Util/UIX.php(50): XF\Template\Templater->widgetPosition('th_footer_uix')
#11 src/addons/ThemeHouse/UIX/Listener/AppPubRenderPage.php(21): ThemeHouse\UIX\Util\UIX->getFooterWidgets(Object(AddonFlare\PaidRegistrations\XF\Template\Templater))
#12 [internal function]: ThemeHouse\UIX\Listener\AppPubRenderPage::appPubRenderPage(Object(XF\Pub\App), Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#13 src/XF/Extension.php(67): call_user_func_array(Array, Array)
#14 src/XF/App.php(2647): XF\Extension->fire('app_pub_render_...', Array, NULL)
#15 src/XF/Pub/App.php(545): XF\App->fire('app_pub_render_...', Array)
#16 src/XF/App.php(1988): XF\Pub\App->renderPageHtml('
	












...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#17 src/XF/Mvc/Dispatcher.php(362): XF\App->renderPage('
	












...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#18 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#19 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#20 src/XF.php(390): XF\App->run()
#21 index.php(20): XF::runApp('XF\\Pub\\App')
#22 {main}

Request state

array(4) {
  ["url"] => string(40) "/threads/choti-by-songrahok.35791/page-3"
  ["referrer"] => string(58) "siteurl"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
````

````
ErrorException: [E_WARNING] Creating default object from empty value src/XF/Widget/Html.php:47 

Generated by: Nirjonmela Mar 23, 2019 at 3:37 PM 

Stack trace

#0 src/XF/Widget/Html.php(47): XF::handlePhpError(2, '[E_WARNING] Cre...', '/home/nadda/pub...', 47, Array)
#1 src/XF/Admin/Controller/Widget.php(121): XF\Widget\Html->verifyOptions(Object(XF\Http\Request), Array, NULL)
#2 src/XF/Mvc/FormAction.php(168): XF\Admin\Controller\Widget->XF\Admin\Controller\{closure}(Object(XF\Mvc\FormAction))
#3 src/XF/Admin/Controller/Widget.php(157): XF\Mvc\FormAction->run()
#4 src/XF/Mvc/Dispatcher.php(321): XF\Admin\Controller\Widget->actionSave(Object(XF\Mvc\ParameterBag))
#5 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Widget', 'Save', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Topics\XF\Admin\Controller\Widget), NULL)
#6 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Topics\XF\Admin\Controller\Widget), NULL)
#7 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#8 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#9 src/XF.php(390): XF\App->run()
#10 admin.php(13): XF::runApp('XF\\Admin\\App')
#11 {main}

Request state

array(4) {
  ["url"] => string(35) "/admin.php?widgets/about-us.41/save"
  ["referrer"] => string(57) "/admin.php?widgets/about-us.41/edit"
  ["_GET"] => array(1) {
    ["widgets/about-us_41/save"] => string(0) ""
  }
  ["_POST"] => array(10) {
    ["definition_id"] => string(4) "html"
    ["widget_key"] => string(26) "thuix_footer_aboutUsWidget"
    ["title"] => string(8) "About us"
    ["positions"] => array(1) {
      ["th_footer_uix"] => string(2) "10"
    }
    ["display_condition"] => string(0) ""
    ["options"] => array(3) {
      ["template"] => string(0) ""
      ["advanced_mode"] => string(1) "1"
      ["template_title"] => string(27) "_widget_thuix_aboutUsWidget"
    }
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(35) "/admin.php?widgets/about-us.41/edit"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

````
ErrorException: [E_NOTICE] Trying to get property 'title' of non-object src/XF/Widget/Html.php:45 

Generated by: Nirjonmela Mar 23, 2019 at 3:37 PM 

Stack trace

#0 src/XF/Widget/Html.php(45): XF::handlePhpError(8, '[E_NOTICE] Tryi...', '/home/nadda/pub...', 45, Array)
#1 src/XF/Admin/Controller/Widget.php(121): XF\Widget\Html->verifyOptions(Object(XF\Http\Request), Array, NULL)
#2 src/XF/Mvc/FormAction.php(168): XF\Admin\Controller\Widget->XF\Admin\Controller\{closure}(Object(XF\Mvc\FormAction))
#3 src/XF/Admin/Controller/Widget.php(157): XF\Mvc\FormAction->run()
#4 src/XF/Mvc/Dispatcher.php(321): XF\Admin\Controller\Widget->actionSave(Object(XF\Mvc\ParameterBag))
#5 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Widget', 'Save', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Topics\XF\Admin\Controller\Widget), NULL)
#6 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Topics\XF\Admin\Controller\Widget), NULL)
#7 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#8 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#9 src/XF.php(390): XF\App->run()
#10 admin.php(13): XF::runApp('XF\\Admin\\App')
#11 {main}

Request state

array(4) {
  ["url"] => string(35) "/admin.php?widgets/about-us.41/save"
  ["referrer"] => string(57) "/admin.php?widgets/about-us.41/edit"
  ["_GET"] => array(1) {
    ["widgets/about-us_41/save"] => string(0) ""
  }
  ["_POST"] => array(10) {
    ["definition_id"] => string(4) "html"
    ["widget_key"] => string(26) "thuix_footer_aboutUsWidget"
    ["title"] => string(8) "About us"
    ["positions"] => array(1) {
      ["th_footer_uix"] => string(2) "10"
    }
    ["display_condition"] => string(0) ""
    ["options"] => array(3) {
      ["template"] => string(0) ""
      ["advanced_mode"] => string(1) "1"
      ["template_title"] => string(27) "_widget_thuix_aboutUsWidget"
    }
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(35) "/admin.php?widgets/about-us.41/edit"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

````
ErrorException: Template error: Template public:_widget_thuix_quickNavWidget is unknown src/XF/Template/Templater.php:618 

Generated by: boil26 Mar 23, 2019 at 3:37 PM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nadda/pub...', 618, Array)
#1 src/XF/Template/Templater.php(618): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(566): XF\Template\Templater->getTemplateData('public', '_widget_thuix_q...')
#3 src/XF/Template/Templater.php(1300): XF\Template\Templater->getTemplateCode('public', '_widget_thuix_q...')
#4 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('_widget_thuix_q...', Array, true)
#5 src/XF/Widget/Html.php(16): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:_widget_...', Array)
#6 internal_data/code_cache/widgets/_42_thuix_footer_quickNavWidget.php(5): XF\Widget\Html->render()
#7 src/XF/Template/Templater.php(6649): XF\SubContainer\Widget->{closure}(Object(AddonFlare\PaidRegistrations\XF\Template\Templater), Array, Array)
#8 src/XF/SubContainer/Widget.php(168): XF\Template\Templater->renderWidgetClosure(Object(Closure), Array)
#9 src/XF/Template/Templater.php(1620): XF\SubContainer\Widget->getCompiledWidget(Array, Array)
#10 src/addons/ThemeHouse/UIX/Util/UIX.php(50): XF\Template\Templater->widgetPosition('th_footer_uix')
#11 src/addons/ThemeHouse/UIX/Listener/AppPubRenderPage.php(21): ThemeHouse\UIX\Util\UIX->getFooterWidgets(Object(AddonFlare\PaidRegistrations\XF\Template\Templater))
#12 [internal function]: ThemeHouse\UIX\Listener\AppPubRenderPage::appPubRenderPage(Object(XF\Pub\App), Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#13 src/XF/Extension.php(67): call_user_func_array(Array, Array)
#14 src/XF/App.php(2647): XF\Extension->fire('app_pub_render_...', Array, NULL)
#15 src/XF/Pub/App.php(545): XF\App->fire('app_pub_render_...', Array)
#16 src/XF/App.php(1988): XF\Pub\App->renderPageHtml('
	












...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#17 src/XF/Mvc/Dispatcher.php(362): XF\App->renderPage('
	












...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#18 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#19 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#20 src/XF.php(390): XF\App->run()
#21 index.php(20): XF::runApp('XF\\Pub\\App')
#22 {main}

Request state

array(4) {
  ["url"] => string(40) "/threads/choti-by-songrahok.35791/page-3"
  ["referrer"] => string(58) "/forums/self-written-choti.90/page-4"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
````

````
ErrorException: Template error: Template public:_widget_thuix_userNavWidget is unknown src/XF/Template/Templater.php:618 

Generated by: boil26 Mar 23, 2019 at 3:37 PM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nadda/pub...', 618, Array)
#1 src/XF/Template/Templater.php(618): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(566): XF\Template\Templater->getTemplateData('public', '_widget_thuix_u...')
#3 src/XF/Template/Templater.php(1300): XF\Template\Templater->getTemplateCode('public', '_widget_thuix_u...')
#4 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('_widget_thuix_u...', Array, true)
#5 src/XF/Widget/Html.php(16): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:_widget_...', Array)
#6 internal_data/code_cache/widgets/_43_thuix_footer_userNavWidget.php(5): XF\Widget\Html->render()
#7 src/XF/Template/Templater.php(6649): XF\SubContainer\Widget->{closure}(Object(AddonFlare\PaidRegistrations\XF\Template\Templater), Array, Array)
#8 src/XF/SubContainer/Widget.php(168): XF\Template\Templater->renderWidgetClosure(Object(Closure), Array)
#9 src/XF/Template/Templater.php(1620): XF\SubContainer\Widget->getCompiledWidget(Array, Array)
#10 src/addons/ThemeHouse/UIX/Util/UIX.php(50): XF\Template\Templater->widgetPosition('th_footer_uix')
#11 src/addons/ThemeHouse/UIX/Listener/AppPubRenderPage.php(21): ThemeHouse\UIX\Util\UIX->getFooterWidgets(Object(AddonFlare\PaidRegistrations\XF\Template\Templater))
#12 [internal function]: ThemeHouse\UIX\Listener\AppPubRenderPage::appPubRenderPage(Object(XF\Pub\App), Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#13 src/XF/Extension.php(67): call_user_func_array(Array, Array)
#14 src/XF/App.php(2647): XF\Extension->fire('app_pub_render_...', Array, NULL)
#15 src/XF/Pub/App.php(545): XF\App->fire('app_pub_render_...', Array)
#16 src/XF/App.php(1988): XF\Pub\App->renderPageHtml('
	












...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#17 src/XF/Mvc/Dispatcher.php(362): XF\App->renderPage('
	












...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#18 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#19 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#20 src/XF.php(390): XF\App->run()
#21 index.php(20): XF::runApp('XF\\Pub\\App')
#22 {main}

Request state

array(4) {
  ["url"] => string(40) "/threads/choti-by-songrahok.35791/page-3"
  ["referrer"] => string(58) "/forums/self-written-choti.90/page-4"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by jonw316** [comment]
To get rid of this error, you will need to remove any widgets that have been corrupted. In this case it is the quick nav widget, the user nav widget and the about us widget. You will then need to recreate those widgets.

**Comment by Nirjonadda** [comment]
@jonw316 How to recreate those widgets? I have seen can only add with HTML but what code need to use?

![ScreenShot00962](https://user-images.githubusercontent.com/6899856/54872435-4d75b800-4dc4-11e9-93a0-384c58d55a58.png)

**Comment by Nirjonadda** [comment]
@jonw316 I am still can not create those widgets without HTML code. Please do you have any update that how can add?

**Comment by jonw316** [comment]
```
<div class="block" data-widget-definition="th_aboutUs">
    <div class="block-container block-container--noStripRadius">
        <h3 class="block-minorHeader">About us</h3>
        <ul class="block-body">
            <li class="block-row">Our community has been around for many years and pride ourselves on offering unbiased, critical discussion among people of all different backgrounds. We are working every day to make sure our community is one of the best.</li>
        </ul>
    </div>
</div>
```

```
<div class="block" data-widget-definition="th_navigation">
    <div class="block-container block-container--noStripRadius">
        <h3 class="block-minorHeader">Quick Navigation</h3>
        <div class="block-body">
            <xf:if is="$xf.options.homePageUrl">
            <a class="blockLink rippleButton" href="{$xf.options.homePageUrl}">{{ phrase('home') }}</a>
            </xf:if>
            <a class="blockLink rippleButton" href="{{ link('forums') }}">{{ phrase('forums') }}</a>
            <xf:if is="$xf.visitor.canUseContactForm()">
                <xf:if is="$xf.options.contactUrl.type == 'default'">
                    <a class="blockLink rippleButton" href="{{ link('misc/contact') }}" data-xf-click="overlay">{{ phrase('contact_us') }}</a>
                <xf:elseif is="$xf.options.contactUrl.type == 'custom'" />
                    <a class="blockLink rippleButton" href="{$xf.options.contactUrl.custom}" data-xf-click="{{ $xf.options.contactUrl.overlay ? 'overlay' : '' }}">{{ phrase('contact_us') }}</a>
                </xf:if>
            </xf:if>
        </div>
    </div>
</div>
```

```
<div class="block" data-widget-definition="th_userNavigation">
    <div class="block-container block-container--noStripRadius">
        <h3 class="block-minorHeader">User Menu</h3>
        <div class="block-body">
            <xf:if is="$xf.visitor.user_id">
                <a class="blockLink rippleButton" href="{{ link('members', $xf.visitor) }}">{{ phrase('th_profile_uix') }}</a>
                <a class="blockLink rippleButton" href="{{ link('account/account-details') }}">{{ phrase('account_details') }}</a>
                <a class="blockLink rippleButton" href="{{ link('whats-new/news-feed') }}">{{ phrase('news_feed') }}</a>
                <a class="blockLink rippleButton" href="{{ link('logout', null, {'t': csrf_token()}) }}">{{ phrase('log_out') }}</a>
            <xf:else />
                <a class="blockLink rippleButton" href="{{ link('login') }}">{{ phrase('login') }}</a>
            </xf:if>
        </div>
    </div>
</div>
```

**Comment by Nirjonadda** [comment]
Does not need adding `Display condition`?

**Comment by jonw316** [comment]
Nope
