### ISSUE TITLE
[UI.X Pro] - Template error: Template public:uix_icons.less is unknown

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#1246]
Server error log with Xenforo 2.2

```
ErrorException: Template error: Template public:uix_icons.less is unknown src/XF/Template/Templater.php:663 

Generated by: Unknown account Oct 1, 2020 at 4:06 AM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nadda/pub...', 663, Array)
#1 src/XF/Template/Templater.php(663): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(625): XF\Template\Templater->getTemplateData('public', 'uix_icons.less')
#3 src/XF/Template/Templater.php(744): XF\Template\Templater->getTemplateMacro('public', 'uix_icons.less', 'content')
#4 internal_data/code_cache/templates/l1/s9/public/app.less.php(127): XF\Template\Templater->callMacro('uix_icons.less', 'content', Array, Array)
#5 src/XF/Template/Templater.php(1608): XF\Template\Templater->{closure}(Object(AddonFlare\PaidRegistrations\XF\Template\Templater), Array, NULL)
#6 src/XF/CssRenderer.php(331): XF\Template\Templater->renderTemplate('app.less', Array, false)
#7 src/XF/CssRenderer.php(258): XF\CssRenderer->renderTemplate('public:app.less', NULL)
#8 src/addons/ThemeHouse/UIX/XF/CssRenderer.php(40): XF\CssRenderer->renderTemplates(Array, Array, Array)
#9 src/XF/CssRenderer.php(116): ThemeHouse\UIX\XF\CssRenderer->renderTemplates(Array, Array, Array)
#10 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#11 src/addons/SV/RedisCache/XF/CssWriter.php(49): XF\CssWriter->run(Array, 9, 1, 'adc2626b697d8df...')
#12 css.php(30): SV\RedisCache\XF\CssWriter->run(Array, 9, 1, 'adc2626b697d8df...')
#13 {main}

Request state

array(4) {
  ["url"] => string(158) "/css.php?css=public%3Anormalize.css%2Cpublic%3Afa.css%2Cpublic%3Acore.less%2Cpublic%3Aapp.less&s=9&l=1&d=1601497824&k=adc2626b697d8df7ae73744f25e39ffa6a80c73b"
  ["referrer"] => string(37) "/search/136192/"
  ["_GET"] => array(5) {
    ["css"] => string(67) "public:normalize.css,public:fa.css,public:core.less,public:app.less"
    ["s"] => string(1) "9"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1601497824"
    ["k"] => string(40) "adc2626b697d8df7ae73744f25e39ffa6a80c73b"
  }
  ["_POST"] => array(0) {
  }
}
```

```
ErrorException: Template error: Macro public:uix_icons.less:content is unknown src/XF/Template/Templater.php:631 

Generated by: Unknown account Oct 1, 2020 at 4:06 AM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Macro public:ui...', '/home/nadda/pub...', 631, Array)
#1 src/XF/Template/Templater.php(631): trigger_error('Macro public:ui...', 512)
#2 src/XF/Template/Templater.php(744): XF\Template\Templater->getTemplateMacro('public', 'uix_icons.less', 'content')
#3 internal_data/code_cache/templates/l1/s9/public/app.less.php(127): XF\Template\Templater->callMacro('uix_icons.less', 'content', Array, Array)
#4 src/XF/Template/Templater.php(1608): XF\Template\Templater->{closure}(Object(AddonFlare\PaidRegistrations\XF\Template\Templater), Array, NULL)
#5 src/XF/CssRenderer.php(331): XF\Template\Templater->renderTemplate('app.less', Array, false)
#6 src/XF/CssRenderer.php(258): XF\CssRenderer->renderTemplate('public:app.less', NULL)
#7 src/addons/ThemeHouse/UIX/XF/CssRenderer.php(40): XF\CssRenderer->renderTemplates(Array, Array, Array)
#8 src/XF/CssRenderer.php(116): ThemeHouse\UIX\XF\CssRenderer->renderTemplates(Array, Array, Array)
#9 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#10 src/addons/SV/RedisCache/XF/CssWriter.php(49): XF\CssWriter->run(Array, 9, 1, 'adc2626b697d8df...')
#11 css.php(30): SV\RedisCache\XF\CssWriter->run(Array, 9, 1, 'adc2626b697d8df...')
#12 {main}

Request state

array(4) {
  ["url"] => string(158) "/css.php?css=public%3Anormalize.css%2Cpublic%3Afa.css%2Cpublic%3Acore.less%2Cpublic%3Aapp.less&s=9&l=1&d=1601497824&k=adc2626b697d8df7ae73744f25e39ffa6a80c73b"
  ["referrer"] => string(37) "/search/136192/"
  ["_GET"] => array(5) {
    ["css"] => string(67) "public:normalize.css,public:fa.css,public:core.less,public:app.less"
    ["s"] => string(1) "9"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1601497824"
    ["k"] => string(40) "adc2626b697d8df7ae73744f25e39ffa6a80c73b"
  }
  ["_POST"] => array(0) {
  }
}
```

**Comment by Ian-Hitt** [comment]
You'll need to update your outdated templates, and if you've used uix_icons.less in anything custom on your end, you will have to update it there as well.

**Comment by Nirjonadda** [comment]
@Ian-Hitt How to update outdated templates? Only [this one](https://github.com/Audentio/xf2theme-issues/issues/1247) are outdated templates. We have not added any custom code in uix_icons.less templates.
