### ISSUE TITLE
     TypeError: Template public:moc_post_macros error: Argument 1 passed to XF\Entity\User::canStartConversationWith() must be an instance of XF\Entity\User, null given src/XF/Entity/User.php:920 

### ISSUE THREAD

**Issue by zadr04-apps** [Audentio/xf2theme-issues#1272]
#0 [internal function]: XF\Entity\User->canStartConversationWith(NULL)
#1 src/XF/Template/Templater.php(1166): call_user_func_array(Array, Array)
#2 internal_data/code_cache/templates/l4/s74/public/moc_post_macros.php(7): XF\Template\Templater->method(Object(MMO\ImpersonateUser\XF\Entity\User), 'canStartConvers...', Array)
#3 src/XF/Template/Templater.php(1609): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, NULL)
#4 src/addons/BR/ModernStatistic/XF/Template/Templater.php(27): XF\Template\Templater->renderTemplate('moc_post_macros', Array, true)
#5 src/XF/Template/Templater.php(1638): BR\ModernStatistic\XF\Template\Templater->renderTemplate('public:moc_post...', Array)
#6 internal_data/code_cache/templates/l4/s74/public/post_macros.php(798): XF\Template\Templater->includeTemplate('public:moc_post...', Array)
#7 src/XF/Template/Templater.php(799): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, NULL)
#8 internal_data/code_cache/templates/l4/s74/public/post_macros.php(728): XF\Template\Templater->callMacro('post_macros', 'post_action_bar', Array, Array)
#9 src/XF/Template/Templater.php(799): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, NULL)
#10 internal_data/code_cache/templates/l4/s74/public/post_macros.php(126): XF\Template\Templater->callMacro('post_macros', 'post_footer', Array, Array)
#11 src/XF/Template/Templater.php(962): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, Object(XF\Template\ExtensionSet))
#12 src/XF/Template/Templater.php(898): XF\Template\Templater->renderExtensionInternal('footer', Array, Array, Object(XF\Template\ExtensionSet))
#13 internal_data/code_cache/templates/l4/s74/public/post_macros.php(151): XF\Template\Templater->renderExtension('footer', Array, Object(XF\Template\ExtensionSet))
#14 src/XF/Template/Templater.php(962): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, Object(XF\Template\ExtensionSet))
#15 src/XF/Template/Templater.php(898): XF\Template\Templater->renderExtensionInternal('main_cell_inner', Array, Array, Object(XF\Template\ExtensionSet))
#16 internal_data/code_cache/templates/l4/s74/public/post_macros.php(162): XF\Template\Templater->renderExtension('main_cell_inner', Array, Object(XF\Template\ExtensionSet))
#17 src/XF/Template/Templater.php(962): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, Object(XF\Template\ExtensionSet))
#18 src/XF/Template/Templater.php(898): XF\Template\Templater->renderExtensionInternal('main_cell', Array, Array, Object(XF\Template\ExtensionSet))
#19 internal_data/code_cache/templates/l4/s74/public/post_macros.php(174): XF\Template\Templater->renderExtension('main_cell', Array, Object(XF\Template\ExtensionSet))
#20 src/XF/Template/Templater.php(962): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, Object(XF\Template\ExtensionSet))
#21 src/XF/Template/Templater.php(898): XF\Template\Templater->renderExtensionInternal('full_body', Array, Array, Object(XF\Template\ExtensionSet))
#22 internal_data/code_cache/templates/l4/s74/public/post_macros.php(217): XF\Template\Templater->renderExtension('full_body', Array, Object(XF\Template\ExtensionSet))
#23 src/XF/Template/Templater.php(799): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, Object(XF\Template\ExtensionSet))
#24 internal_data/code_cache/templates/l4/s74/public/thread_view.php(1019): XF\Template\Templater->callMacro('post_macros', 'post', Array, Array)
#25 src/XF/Template/Templater.php(1609): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, Object(XF\Template\ExtensionSet))
#26 src/addons/BR/ModernStatistic/XF/Template/Templater.php(27): XF\Template\Templater->renderTemplate('thread_view', Array, true)
#27 src/XF/Template/Template.php(24): BR\ModernStatistic\XF\Template\Templater->renderTemplate('public:thread_v...', Array)
#28 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#29 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Html->renderView('XF:Thread\\View', 'public:thread_v...', Array)
#30 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#31 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#32 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#33 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#34 src/XF.php(465): XF\App->run()
#35 index.php(20): XF::runApp('XF\\Pub\\App')
#36 {main}

**Comment by zadr04-apps** [comment]
array(4) {
  ["url"] => string(12) "/6718/page-3"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by zadr04-apps** [comment]
Unable to disable [SV]StandardLib aslike fresh updated [Brivium] ModernStatistic.
How to fix that crap, throwed dozen of times daily?
